language: cpp
compiler: gcc
dist: bionic

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: 
  # Build and run the tests
  - qmake gausser_test.pro
  - make debug
  - ./gausser_test
  # Build and run the command line application
  - qmake gausser.pro
  - make release
  - ./gausser
  # Code coverage
  - ./get_code_cov >/dev/null
  - codecov >/dev/null
  # OCLint
  - ./do_oclint

after_success:
  - bash <(curl -s https://codecov.io/bash)

